### ISSUE TITLE
v1.3.1-beta2 is picked over v1.3.1

### ISSUE THREAD

**Issue by ruudk** [oprypin/find-latest-tag#9]
I have a situation where this acton successfully choose `v1.3.1-beta2` over `v1.3.1-beta1` but as soon as I published `v1.3.1` (GM) it still preferred `v1.3.1-beta2`.

Can this be handled?

**Comment by oprypin** [comment]
I don't have immediate plans to handle this. Nontrivial to figure out which things after `-` should increase the version and which should decrease. Also backwards incompatible.

This follows a different format of specifying beta versions - see
https://github.com/oprypin/tag-cmp#readme
https://github.com/oprypin/tag-cmp/blob/4985e45b8378eb2568a19f5cd46b50446432aed7/tags.js#L15
https://peps.python.org/pep-0440/#pre-releases

That is, you're expected to use the format `v1.3.1b2` not `v1.3.1-beta2`, then it works
